### ISSUE TITLE
Learn More link broken

### ISSUE THREAD

**Issue by dcmid** [rLoopTeam/website#58]
If I click the learn more link I am taken to a page that says "you are not allowed to do that -- wiki_disabled"
![image](https://cloud.githubusercontent.com/assets/7914186/9226889/5a3d3d82-40d6-11e5-9037-a878da378b61.png)

**Comment by zlsa** [comment]
I think the webdev team is switching servers soon (right now they're not able to update the main site).

**Comment by jdublu10** [comment]
Yep. That's the current situation. Will close this issue once we're transferred over.
